Add a second instance

diff --git a/main.yml b/main.yml
--- a/main.yml
+++ b/main.yml
@@ -6,11 +6,6 @@ Parameters:
   EC2AMI:
     Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
     Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
-  Domain:
-    Type: String
-  Certificate:
-    Type: String
-    Description: 'An existing ACM certificate ARN for your domain'
   CodePipelineBucket:
     Type: String
     Description: 'The S3 bucket for CodePipeline artifacts.'
@@ -27,9 +22,55 @@ Parameters:
   GitHubPersonalAccessToken:
     Type: String
     NoEcho: true
-    Description: 'A GitHub personal access token with "repo" and "admin:repo_hook" permissions.'
+    Description: 'A GitHub personal access token with "repo" and
+"admin:repo_hook" permissions.'
+
 
 Resources:
+
+  SecurityGroup:
+    Type: "AWS::EC2::SecurityGroup"
+    Properties:
+      GroupDescription: !Sub 'Internal Security group for ${AWS::StackName}'
+      SecurityGroupIngress:
+        - IpProtocol: tcp
+          FromPort: 8080
+          ToPort: 8080
+          CidrIp: 0.0.0.0/0
+        - IpProtocol: tcp
+          FromPort: 22
+          ToPort: 22
+          CidrIp: 0.0.0.0/0
+      Tags:
+        - Key: Name
+          Value: !Ref AWS::StackName
+
+  InstanceRole:
+    Type: "AWS::IAM::Role"
+    Properties:
+      AssumeRolePolicyDocument:
+        Version: "2012-10-17"
+        Statement:
+          Effect: Allow
+          Principal:
+            Service:
+              - "ec2.amazonaws.com"
+          Action: sts:AssumeRole
+      ManagedPolicyArns:
+        - arn:aws:iam::aws:policy/CloudWatchFullAccess
+        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy
+      Policies:
+        - PolicyName: ec2DescribeTags
+          PolicyDocument:
+            Version: 2012-10-17
+            Statement:
+              - Effect: Allow
+                Action: 'ec2:DescribeTags'
+                Resource: '*'
+      Tags:
+        - Key: Name
+          Value: !Ref AWS::StackName
+
   DeploymentRole:
     Type: AWS::IAM::Role
     Properties:
@@ -44,7 +85,13 @@ Resources:
               - codebuild.amazonaws.com
           Action: sts:AssumeRole
       ManagedPolicyArns:
-        - arn:aws:iam::aws:policy/PowerUserAccess
+        - arn:aws:iam::aws:policy/AmazonS3FullAccess
+        - arn:aws:iam::aws:policy/CloudWatchFullAccess
+        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
+        - arn:aws:iam::aws:policy/AWSCodePipeline_FullAccess
+        - arn:aws:iam::aws:policy/AWSCodeDeployDeployerAccess
+        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
+        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole
 
   BuildProject:
     Type: AWS::CodeBuild::Project
@@ -68,23 +115,16 @@ Resources:
 
   StagingDeploymentGroup:
     Type: AWS::CodeDeploy::DeploymentGroup
+    DependsOn: Instance
     Properties:
       DeploymentGroupName: staging
-      AutoScalingGroups:
-        - !GetAtt Staging.Outputs.ScalingGroup
       ApplicationName: !Ref DeploymentApplication
       DeploymentConfigName: CodeDeployDefault.AllAtOnce
       ServiceRoleArn: !GetAtt DeploymentRole.Arn
-
-  ProdDeploymentGroup:
-    Type: AWS::CodeDeploy::DeploymentGroup
-    Properties:
-      DeploymentGroupName: prod
-      AutoScalingGroups:
-        - !GetAtt Prod.Outputs.ScalingGroup
-      ApplicationName: !Ref DeploymentApplication
-      DeploymentConfigName: CodeDeployDefault.OneAtATime
-      ServiceRoleArn: !GetAtt DeploymentRole.Arn
+      Ec2TagFilters:
+        - Key: aws:cloudformation:stack-name
+          Type: KEY_AND_VALUE
+          Value: !Ref AWS::StackName
 
   Pipeline:
     Type: AWS::CodePipeline::Pipeline
@@ -141,20 +181,6 @@ Resources:
                 ApplicationName: !Ref DeploymentApplication
                 DeploymentGroupName: !Ref StagingDeploymentGroup
               RunOrder: 1
-        - Name: Prod
-          Actions:
-            - Name: Prod
-              InputArtifacts:
-                - Name: Build
-              ActionTypeId:
-                Category: Deploy
-                Owner: AWS
-                Version: 1
-                Provider: CodeDeploy
-              Configuration:
-                ApplicationName: !Ref DeploymentApplication
-                DeploymentGroupName: !Ref ProdDeploymentGroup
-              RunOrder: 1
 
   PipelineWebhook:
     Type: AWS::CodePipeline::Webhook
@@ -171,40 +197,123 @@ Resources:
       TargetPipelineVersion: !GetAtt Pipeline.Version
       RegisterWithThirdParty: true
 
-  Staging:
-    Type: AWS::CloudFormation::Stack
+  InstanceProfile:
+    Type: "AWS::IAM::InstanceProfile"
     Properties:
-      TemplateURL: stage.yml
-      TimeoutInMinutes: 30
-      Parameters:
-        EC2InstanceType: !Ref EC2InstanceType
-        EC2AMI: !Ref EC2AMI
-        Domain: !Ref Domain
-        SubDomain: staging
-        Certificate: !Ref Certificate
+      Roles:
+        - Ref: InstanceRole
 
-  Prod:
-    Type: AWS::CloudFormation::Stack
-    DependsOn: Staging
+  Instance:
+    Type: AWS::EC2::Instance
+    CreationPolicy:
+      ResourceSignal:
+        Timeout: PT5M
+        Count: 1
     Properties:
-      TemplateURL: stage.yml
-      TimeoutInMinutes: 30
-      Parameters:
-        EC2InstanceType: !Ref EC2InstanceType
-        EC2AMI: !Ref EC2AMI
-        Domain: !Ref Domain
-        SubDomain: prod
-        Certificate: !Ref Certificate
+      LaunchTemplate:
+        LaunchTemplateId: !Ref InstanceLaunchTemplate
+        Version: !GetAtt InstanceLaunchTemplate.LatestVersionNumber
+      Tags:
+        - Key: Name
+          Value: !Ref AWS::StackName
+
+  Instance2:
+    Type: AWS::EC2::Instance
+    CreationPolicy:
+      ResourceSignal:
+        Timeout: PT5M
+        Count: 1
+    Properties:
+      LaunchTemplate:
+        LaunchTemplateId: !Ref InstanceLaunchTemplate
+        Version: !GetAtt InstanceLaunchTemplate.LatestVersionNumber
+      Tags:
+        - Key: Name
+          Value: !Ref AWS::StackName
+
+  InstanceLaunchTemplate:
+    Type: AWS::EC2::LaunchTemplate
+    Metadata:
+      AWS::CloudFormation::Init:
+        config:
+          packages:
+            yum:
+              ruby: []
+              jq: []
+          files:
+            /home/ec2-user/install:
+              source: !Sub "https://aws-codedeploy-${AWS::Region}.s3.amazonaws.com/latest/install"
+              mode: "000755" # executable
+          commands:
+            00-install-cd-agent:
+              command: "./install auto"
+              cwd: "/home/ec2-user/"
+    Properties:
+      LaunchTemplateName: !Sub 'LaunchTemplate_${AWS::StackName}'
+      LaunchTemplateData:
+        ImageId: !Ref EC2AMI
+        InstanceType: !Ref EC2InstanceType
+        IamInstanceProfile:
+          Arn: !GetAtt InstanceProfile.Arn
+        Monitoring:
+          Enabled: true
+        SecurityGroupIds:
+          - !GetAtt SecurityGroup.GroupId
+        UserData:
+          Fn::Base64: !Sub |
+            #!/bin/bash -xe
+
+            # send script output to /tmp so we can debug boot failures
+            exec > /tmp/userdata.log 2>&1 
+
+            # Update all packages
+            yum -y update
+
+            # Get latest cfn scripts; https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/best-practices.html#cfninit
+            yum install -y aws-cfn-bootstrap
+            
+            cat > /tmp/install_script.sh << EOF 
+              # START
+              echo "Setting up NodeJS Environment"
+              curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
+
+              # Dot source the files to ensure that variables are available within the current shell
+              . /home/ec2-user/.nvm/nvm.sh
+              . /home/ec2-user/.bashrc
+
+              # Install NVM, NPM, Node.JS
+              nvm alias default v12.7.0
+              nvm install v12.7.0
+              nvm use v12.7.0
+
+              # Create log directory
+              mkdir -p /home/ec2-user/app/logs
+            EOF
+
+            chown ec2-user:ec2-user /tmp/install_script.sh && chmod a+x /tmp/install_script.sh
+            sleep 1; sudo su - ec2-user -c "/tmp/install_script.sh" 
+
+            # Have CloudFormation install any files and packages from the metadata
+            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource InstanceLaunchTemplate
+
+            # Query the EC2 metadata service for this instance's instance-id
+            export INSTANCE_ID="`wget -q -O - http://169.254.169.254/latest/meta-data/instance-id`"
+
+            # Query EC2 describeTags method and pull our the CFN Logical ID for this instance
+
+            export LOGICAL_ID=`aws --region ${AWS::Region} ec2 describe-tags --filters "Name=resource-id,Values=${!INSTANCE_ID}" "Name=key,Values=aws:cloudformation:logical-id" | jq -r ".Tags[0].Value"`
+
+            # Signal to CloudFormation that the instance is ready
+            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region} --resource ${!LOGICAL_ID}
 
 Outputs:
-  StagingHTTPSLBEndpoint:
-    Description: The DNS name for the staging HTTPS LB
-    Value: !GetAtt Staging.Outputs.HTTPSEndpoint
-    Export:
-      Name: StagingHTTPSLBEndpoint
-  ProdHTTPSLBEndpoint:
-    Description: The DNS name for the prod HTTPS LB
-    Value: !GetAtt Prod.Outputs.HTTPSEndpoint
-    Export:
-      Name: ProdHTTPSLBEndpoint
-
+ InstanceEndpoint1:
+   Description: The DNS name for the created instance
+   Value: !Sub "http://${Instance.PublicDnsName}:8080" 
+   Export:
+     Name: InstanceEndpoint1
+ InstanceEndpoint2:
+   Description: The DNS name for the created instance
+   Value: !Sub "http://${Instance2.PublicDnsName}:8080" 
+   Export:
+     Name: InstanceEndpoint2
